"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var JSSDK_ERRORS;
(function (JSSDK_ERRORS) {
    JSSDK_ERRORS["INVALID_CONFIG_PARAMS"] = "INVALID_CONFIG_PARAMS";
    JSSDK_ERRORS["UNSUPPORTED_TRADE_PAIR"] = "UNSUPPORTED_TRADE_PAIR";
    JSSDK_ERRORS["REQUEST_5S_TIMEOUT"] = "REQUEST_5S_TIMEOUT";
    JSSDK_ERRORS["LESS_THAN_SYSTEM_MIN_TRADE_AMOUNT"] = "LESS_THAN_SYSTEM_MIN_TRADE_AMOUNT";
    JSSDK_ERRORS["GREATER_THAN_SYSTEM_MAX_TRADE_AMOUNT"] = "GREATER_THAN_SYSTEM_MAX_TRADE_AMOUNT";
    JSSDK_ERRORS["LESS_THAN_MM_MIN_TRADE_AMOUNT"] = "LESS_THAN_MM_MIN_TRADE_AMOUNT";
    JSSDK_ERRORS["GREATER_THAN_MM_MAX_TRADE_AMOUNT"] = "GREATER_THAN_MM_MAX_TRADE_AMOUNT";
    JSSDK_ERRORS["CAN_NOT_RESOLVE_EXCHANGE"] = "CAN_NOT_RESOLVE_EXCHANGE";
    JSSDK_ERRORS["NO_DATA_RESPONSED"] = "NO_DATA_RESPONSED";
    JSSDK_ERRORS["INVALID_QUOTE_ID_PARAM"] = "INVALID_QUOTE_ID_PARAM";
    JSSDK_ERRORS["QUOTE_DATA_10S_EXPIRED"] = "QUOTE_DATA_10S_EXPIRED";
    JSSDK_ERRORS["PARAMS_ERROR"] = "PARAMS_ERROR";
    JSSDK_ERRORS["TOKEN_NOT_FOUND"] = "TOKEN_NOT_FOUND";
    JSSDK_ERRORS["NONCE_CONFLICT"] = "NONCE_CONFLICT";
    JSSDK_ERRORS["CONNECT_FAILED"] = "CONNECT_FAILED";
    JSSDK_ERRORS["ALREADY_CONNETING"] = "ALREADY_CONNETING";
    JSSDK_ERRORS["BALANCE_NOT_ENOUGH"] = "BALANCE_NOT_ENOUGH";
    JSSDK_ERRORS["ALLOWANCE_NOT_ENOUGH"] = "ALLOWANCE_NOT_ENOUGH";
})(JSSDK_ERRORS = exports.JSSDK_ERRORS || (exports.JSSDK_ERRORS = {}));
//# sourceMappingURL=errors.js.map